### ISSUE TITLE
🚀 Publish `1.0.0`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-rules-default-jsdoc#10]
## Overview

* Publish version as `1.0.0`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] ~⚙️ Update package version to `1.0.0`~
- [x] Publish.
- [x] #11
- [x] Push version tag `1.0.0` on main

## npm login to GitHub Packages before publishing

* Procedure login as follows:
  1. get login password from your GitHub settings<br>Go to → https://github.com/settings/tokens
  2. copy your `personal access token` created
  3. run in terminal
      ```
      % npm login --registry=https://npm.pkg.github.com/

      Username: your-github-account-in-lower-case-only
      Password:
      Email: your.mail.account@gmail.com
      Logged in as [your-name] on https://npm.pkg.github.com/.
      ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `b46913e`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm login user

  ```
  npm whoami --registry https://npm.pkg.github.com
  ```

- [x] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run 
  npm notice 
  npm notice 📦  @openreachtech/eslint-rules-default-jsdoc@1.0.0
  npm notice === Tarball Contents === 
  npm notice 1.1kB  LICENSE      
  npm notice 3.2kB  README.ja.md 
  npm notice 2.8kB  README.md    
  npm notice 55B    index.js     
  npm notice 126B   index.mjs    
  npm notice 1.0kB  package.json 
  npm notice 15.1kB rules/core.js
  npm notice === Tarball Details === 
  npm notice name:          @openreachtech/eslint-rules-default-jsdoc         
  npm notice version:       1.0.0                                             
  npm notice filename:      openreachtech-eslint-rules-default-jsdoc-1.0.0.tgz
  npm notice package size:  6.1 kB                                            
  npm notice unpacked size: 23.4 kB                                           
  npm notice shasum:        e072e5951bf23e11b2044db9d04ad60b92a77e5f          
  npm notice integrity:     sha512-uHUzyft3RXqFI[...]xD9uCRlonui/w==          
  npm notice total files:   7                                                 
  npm notice 
  npm notice Publishing to https://npm.pkg.github.com with tag latest and default access (dry-run)
  + @openreachtech/eslint-rules-default-jsdoc@1.0.0
  ```

- [x] Check log of `--dry-run` by other member before actual publishing.
- [x] `npm publish`
