### ISSUE TITLE
🚀 Publish `1.0.1`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-rules-default-jsdoc#24]
## Overview

* Publish version as `1.0.1`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #25
- [x] Publish.
- [x] #27
- [x] Push version tag `1.0.1` on main

## npm login to GitHub Packages before publishing

* Procedure login as follows:
  1. get login password from your GitHub settings<br>Go to → https://github.com/settings/tokens
  2. copy your `personal access token` created
  3. run in terminal
      ```
      % npm login --registry=https://npm.pkg.github.com/

      Username: your-github-account-in-lower-case-only
      Password:
      Email: your.mail.account@gmail.com
      Logged in as [your-name] on https://npm.pkg.github.com/.
      ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `ae1d0b3`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm login user

  ```
  npm whoami --registry https://npm.pkg.github.com
  ```

- [x] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run
  npm notice 
  npm notice 📦  @openreachtech/eslint-rules-default-jsdoc@1.0.1
  npm notice === Tarball Contents === 
  npm notice 1.1kB  LICENSE         
  npm notice 3.2kB  README.ja.md    
  npm notice 2.8kB  README.md       
  npm notice 55B    index.js        
  npm notice 126B   index.mjs       
  npm notice 1.0kB  package.json    
  npm notice 15.1kB rules/core.js   
  npm notice 172B   types/index.d.ts
  npm notice === Tarball Details === 
  npm notice name:          @openreachtech/eslint-rules-default-jsdoc         
  npm notice version:       1.0.1                                             
  npm notice filename:      openreachtech-eslint-rules-default-jsdoc-1.0.1.tgz
  npm notice package size:  6.2 kB                                            
  npm notice unpacked size: 23.5 kB                                           
  npm notice shasum:        e56a396d8ea22249c8aed5e3d4cc8f92ee669a45          
  npm notice integrity:     sha512-tAtLGZGmG/6mT[...]Fn5JqS0RSEOnA==          
  npm notice total files:   8                                                 
  npm notice 
  npm notice Publishing to https://npm.pkg.github.com with tag latest and default access (dry-run)
  + @openreachtech/eslint-rules-default-jsdoc@1.0.1
  ```

- [x] Check log of `--dry-run` by other member before actual publishing.
- [ ] `npm publish`

**Comment by hecticme** [comment]
🚀

```
npm notice
npm notice 📦  @openreachtech/eslint-rules-default-jsdoc@1.0.1
npm notice Tarball Contents
npm notice 1.1kB LICENSE
npm notice 3.2kB README.ja.md
npm notice 2.8kB README.md
npm notice 55B index.js
npm notice 126B index.mjs
npm notice 1.0kB package.json
npm notice 15.1kB rules/core.js
npm notice 172B types/index.d.ts
npm notice Tarball Details
npm notice name: @openreachtech/eslint-rules-default-jsdoc
npm notice version: 1.0.1
npm notice filename: openreachtech-eslint-rules-default-jsdoc-1.0.1.tgz
npm notice package size: 6.2 kB
npm notice unpacked size: 23.5 kB
npm notice shasum: e56a396d8ea22249c8aed5e3d4cc8f92ee669a45
npm notice integrity: sha512-tAtLGZGmG/6mT[...]Fn5JqS0RSEOnA==
npm notice total files: 8
npm notice
npm notice Publishing to https://npm.pkg.github.com with tag latest and default access (dry-run)
+ @openreachtech/eslint-rules-default-jsdoc@1.0.1
```

**Comment by StewEucen** [comment]
* Publish as `1.0.1`
https://github.com/openreachtech/eslint-rules-default-jsdoc/pkgs/npm/eslint-rules-default-jsdoc/223804889
